
python /data1/pky/BELLE/train/generate_llama2_hc3.py --dev_file '/data1/pky/dataset/robustness/hc3_scramble_dataset.json' --model_name_or_path '/data1/pky/output/robustness/trained_model_llama2-hc3-WM-epoch_5_robust_scramble' --output_file '/data1/pky/output/robustness/data_output/1030-hc3-llama2-WM-scramble.json'
python /data1/pky/BELLE/train/generate_llama2_hc3.py --dev_file '/data1/pky/dataset/robustness/hc3_random_replace_dataset.json' --model_name_or_path '/data1/pky/output/robustness/trained_model_llama2-hc3-WM-epoch_5_random_replace' --output_file '/data1/pky/output/robustness/data_output/1030-hc3-llama2-WM-random_replace.json'
python /data1/pky/BELLE/train/generate_llama2_hc3.py --dev_file '/data1/pky/dataset/robustness/hc3_random_insert_dataset.json' --model_name_or_path '/data1/pky/output/robustness/trained_model_llama2-hc3-WM-epoch_5_random_insert' --output_file '/data1/pky/output/robustness/data_output/1030-hc3-llama2-WM-random_insert.json'
python /data1/pky/BELLE/train/generate_llama2_hc3.py --dev_file '/data1/pky/dataset/robustness/hc3_random_delete_dataset.json' --model_name_or_path '/data1/pky/output/robustness/trained_model_llama2-hc3-WM-epoch_5_random_delete' --output_file '/data1/pky/output/robustness/data_output/1030-hc3-llama2-WM-random_delete.json'

python /data1/pky/BELLE/train/generate_llama2_hc3.py --dev_file '/data1/pky/dataset/robustness/wild_scramble_dataset.json' --model_name_or_path '/data1/pky/output/robustness/trained_model_llama2-wild-WM-epoch_5_robust_scramble' --output_file '/data1/pky/output/robustness/data_output/1030-wild-llama2-WM_scramble.json'
python /data1/pky/BELLE/train/generate_llama2_hc3.py --dev_file '/data1/pky/dataset/robustness/wild_random_replace_dataset.json' --model_name_or_path '/data1/pky/output/robustness/trained_model_llama2-wild-WM-epoch_5_robust_random_replace' --output_file '/data1/pky/output/robustness/data_output/1030-wild-llama2-WM-random_replace.json'
python /data1/pky/BELLE/train/generate_llama2_hc3.py --dev_file '/data1/pky/dataset/robustness/wild_random_insert_dataset.json' --model_name_or_path '/data1/pky/output/robustness/trained_model_llama2-wild-WM-epoch_5_robust_random_insert' --output_file '/data1/pky/output/robustness/data_output/1030-wild-llama2-WM-random_insert.json'
python /data1/pky/BELLE/train/generate_llama2_hc3.py --dev_file '/data1/pky/dataset/robustness/wild_random_delete_dataset.json' --model_name_or_path '/data1/pky/output/robustness/trained_model_llama2-wild-WM-epoch_5_robust_random_delete' --output_file '/data1/pky/output/robustness/data_output/1030-wild-llama2-WM-random_delete.json'
