


python /data1/pky/BELLE/train/generate_gpt2_epochsy.py --dev_file='/data1/pky/dataset/Train_for_finetune_1-5158_filter_4234_survival.json' --model_name_or_path='/data1/pky/output/epoch_gpt2/gpt2-WM-hc3-epoch-0.5' --output_file='/data1/pky/output/epoch_gpt2/output_results/1003_WM_hc3_epochs_0.5.json'
python /data1/pky/BELLE/train/generate_gpt2_epochsy.py --dev_file='/data1/pky/dataset/Train_for_finetune_1-5158_filter_4234_survival.json' --model_name_or_path='/data1/pky/output/epoch_gpt2/gpt2-WM-hc3-epoch-0.75' --output_file='/data1/pky/output/epoch_gpt2/output_results/1003_WM_hc3_epochs_0.75.json'
python /data1/pky/BELLE/train/generate_gpt2_epochsy.py --dev_file='/data1/pky/dataset/Train_for_finetune_1-5158_filter_4234_survival.json' --model_name_or_path='/data1/pky/output/epoch_gpt2/gpt2-WM-hc3-epoch-1' --output_file='/data1/pky/output/epoch_gpt2/output_results/1003_WM_hc3_epochs_1.json'
python /data1/pky/BELLE/train/generate_gpt2_epochsy.py --dev_file='/data1/pky/dataset/Train_for_finetune_1-5158_filter_4234_survival.json' --model_name_or_path='/data1/pky/output/epoch_gpt2/gpt2-WM-hc3-epoch-2' --output_file='/data1/pky/output/epoch_gpt2/output_results/1003_WM_hc3_epochs_2.json'
python /data1/pky/BELLE/train/generate_gpt2_epochsy.py --dev_file='/data1/pky/dataset/Train_for_finetune_1-5158_filter_4234_survival.json' --model_name_or_path='/data1/pky/output/epoch_gpt2/gpt2-WM-hc3-epoch-3' --output_file='/data1/pky/output/epoch_gpt2/output_results/1003_WM_hc3_epochs_3.json'
python /data1/pky/BELLE/train/generate_gpt2_epochsy.py --dev_file='/data1/pky/dataset/Train_for_finetune_1-5158_filter_4234_survival.json' --model_name_or_path='/data1/pky/output/epoch_gpt2/gpt2-WM-hc3-epoch-4' --output_file='/data1/pky/output/epoch_gpt2/output_results/1003_WM_hc3_epochs_4.json'
python /data1/pky/BELLE/train/generate_gpt2_epochsy.py --dev_file='/data1/pky/dataset/Train_for_finetune_1-5158_filter_4234_survival.json' --model_name_or_path='/data1/pky/output/epoch_gpt2/gpt2-WM-hc3-epoch-5' --output_file='/data1/pky/output/epoch_gpt2/output_results/1003_WM_hc3_epochs_5.json'
python /data1/pky/BELLE/train/generate_gpt2_epochsy.py --dev_file='/data1/pky/dataset/Train_for_finetune_1-5158_filter_4234_survival.json' --model_name_or_path='/data1/pky/output/epoch_gpt2/gpt2-WM-hc3-epoch-6' --output_file='/data1/pky/output/epoch_gpt2/output_results/1003_WM_hc3_epochs_6.json'
python /data1/pky/BELLE/train/generate_gpt2_epochsy.py --dev_file='/data1/pky/dataset/Train_for_finetune_1-5158_filter_4234_survival.json' --model_name_or_path='/data1/pky/output/epoch_gpt2/gpt2-WM-hc3-epoch-7' --output_file='/data1/pky/output/epoch_gpt2/output_results/1003_WM_hc3_epochs_7.json'
python /data1/pky/BELLE/train/generate_gpt2_epochsy.py --dev_file='/data1/pky/dataset/Train_for_finetune_1-5158_filter_4234_survival.json' --model_name_or_path='/data1/pky/output/epoch_gpt2/gpt2-WM-hc3-epoch-8' --output_file='/data1/pky/output/epoch_gpt2/output_results/1003_WM_hc3_epochs_8.json'
python /data1/pky/BELLE/train/generate_gpt2_epochsy.py --dev_file='/data1/pky/dataset/Train_for_finetune_1-5158_filter_4234_survival.json' --model_name_or_path='/data1/pky/output/epoch_gpt2/gpt2-WM-hc3-epoch-9' --output_file='/data1/pky/output/epoch_gpt2/output_results/1003_WM_hc3_epochs_9.json'



python /data1/pky/BELLE/train/generate_gpt2_epochsy.py --dev_file='/data1/pky/dataset/lastWM.json' --model_name_or_path='/data1/pky/output/epoch_gpt2/gpt2-WM-wild-epoch-0.25' --output_file='/data1/pky/output/epoch_gpt2/output_results/1003_WM_wild_epochs_0.25.json'
python /data1/pky/BELLE/train/generate_gpt2_epochsy.py --dev_file='/data1/pky/dataset/lastWM.json' --model_name_or_path='/data1/pky/output/epoch_gpt2/gpt2-WM-wild-epoch-0.5' --output_file='/data1/pky/output/epoch_gpt2/output_results/1003_WM_wild_epochs_0.5.json'
python /data1/pky/BELLE/train/generate_gpt2_epochsy.py --dev_file='/data1/pky/dataset/lastWM.json' --model_name_or_path='/data1/pky/output/epoch_gpt2/gpt2-WM-wild-epoch-0.75' --output_file='/data1/pky/output/epoch_gpt2/output_results/1003_WM_wild_epochs_0.75.json'
python /data1/pky/BELLE/train/generate_gpt2_epochsy.py --dev_file='/data1/pky/dataset/lastWM.json' --model_name_or_path='/data1/pky/output/epoch_gpt2/gpt2-WM-wild-epoch-1' --output_file='/data1/pky/output/epoch_gpt2/output_results/1003_WM_wild_epochs_1.json'
python /data1/pky/BELLE/train/generate_gpt2_epochsy.py --dev_file='/data1/pky/dataset/lastWM.json' --model_name_or_path='/data1/pky/output/epoch_gpt2/gpt2-WM-wild-epoch-2' --output_file='/data1/pky/output/epoch_gpt2/output_results/1003_WM_wild_epochs_2.json'
python /data1/pky/BELLE/train/generate_gpt2_epochsy.py --dev_file='/data1/pky/dataset/lastWM.json' --model_name_or_path='/data1/pky/output/epoch_gpt2/gpt2-WM-wild-epoch-3' --output_file='/data1/pky/output/epoch_gpt2/output_results/1003_WM_wild_epochs_3.json'
python /data1/pky/BELLE/train/generate_gpt2_epochsy.py --dev_file='/data1/pky/dataset/lastWM.json' --model_name_or_path='/data1/pky/output/epoch_gpt2/gpt2-WM-wild-epoch-4' --output_file='/data1/pky/output/epoch_gpt2/output_results/1003_WM_wild_epochs_4.json'
python /data1/pky/BELLE/train/generate_gpt2_epochsy.py --dev_file='/data1/pky/dataset/lastWM.json' --model_name_or_path='/data1/pky/output/epoch_gpt2/gpt2-WM-wild-epoch-5' --output_file='/data1/pky/output/epoch_gpt2/output_results/1003_WM_wild_epochs_5.json'
python /data1/pky/BELLE/train/generate_gpt2_epochsy.py --dev_file='/data1/pky/dataset/lastWM.json' --model_name_or_path='/data1/pky/output/epoch_gpt2/gpt2-WM-wild-epoch-6' --output_file='/data1/pky/output/epoch_gpt2/output_results/1003_WM_wild_epochs_6.json'
python /data1/pky/BELLE/train/generate_gpt2_epochsy.py --dev_file='/data1/pky/dataset/lastWM.json' --model_name_or_path='/data1/pky/output/epoch_gpt2/gpt2-WM-wild-epoch-7' --output_file='/data1/pky/output/epoch_gpt2/output_results/1003_WM_wild_epochs_7.json'
python /data1/pky/BELLE/train/generate_gpt2_epochsy.py --dev_file='/data1/pky/dataset/lastWM.json' --model_name_or_path='/data1/pky/output/epoch_gpt2/gpt2-WM-wild-epoch-8' --output_file='/data1/pky/output/epoch_gpt2/output_results/1003_WM_wild_epochs_8.json'
python /data1/pky/BELLE/train/generate_gpt2_epochsy.py --dev_file='/data1/pky/dataset/lastWM.json' --model_name_or_path='/data1/pky/output/epoch_gpt2/gpt2-WM-wild-epoch-9' --output_file='/data1/pky/output/epoch_gpt2/output_results/1003_WM_wild_epochs_9.json'